name: WanderingVendors
version: ${project.version}
main: eu.endermite.wanderingvendors.WanderingVendors
api-version: 1.13
authors: [YouHaveTrouble]
description: Make wandering traders useful for once
commands:
  wanderingvendors:
    usage: /wanderingvendors
    permission: wanderingvendors.command
permissions:
  wanderingwendors.command.reload:
    default: OP
    description: Allows usage of reload command
  wanderingvendors.command.createtrade:
    default: OP
    description: Allows creating new trades
  wanderingvendors.comand.trades:
    default: OP
    description: Allows listing and editing trades
